#!/bin/sh
source ../common.sh

# We don't need to actually load nvm for this test
export ZSH_NVM_NO_LOAD=true

# Unset NVM_DIR
unset NVM_DIR

# Check NVM_DIR is unset
[[ -z "$NVM_DIR" ]] || die "NVM_DIR already set"

# Load zsh-nvm
load_zsh_nvm

expected_nvm_dir=$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")
expected_nvm_dir_readable=$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "\$HOME/.nvm" || printf %s "\${XDG_CONFIG_HOME}/nvm")

# Check NVM_DIR is now set to our default
[[ "$NVM_DIR" == "$expected_nvm_dir" ]] || die "\$NVM_DIR wasn't set to $expected_nvm_dir_readable"
